base:
  GRAPHICS_LVGL: 1
  LV_CONF_SKIP: 1
  LV_USE_CLIB_MALLOC: 1
  LV_USE_CLIB_STRING: 1
  LV_USE_CLIB_SPRINTF: 1
  LV_DEF_REFR_PERIOD: 16
  LV_USE_LOG: 1
  LV_LOG_LEVEL_WARN: 1
  LV_LOG_LEVEL: 2
  LV_LOG_PRINTF: 0
  LV_LOG_USE_TIMESTAMP: 0
  LV_USE_FS_POSIX: 1
  LV_FS_POSIX_LETTER: 47
  LV_FS_POSIX_PATH: "/"
  LIB_FREETYPE: 1
  LV_USE_FREETYPE: 1
  LV_USE_NUTTX: 1
  LV_USE_NUTTX_LIBUV: 1
  LV_USE_NUTTX_TOUCHSCREEN: 1

png:
  LIB_PNG: 1
  LV_USE_LIBPNG: 1

jpeg:
  LIB_JPEG_TURBO: 1
  LV_USE_LIBJPEG_TURBO: 1

gif:
  LV_USE_GIF: y
  LV_FS_POSIX_CACHE_SIZE: 4096

cache:
  LV_CACHE_DEF_SIZE: 8388608
  LV_IMAGE_HEADER_CACHE_DEF_CNT: 128
  LV_FREETYPE_CACHE_SIZE: 1024
  LV_FREETYPE_CACHE_FT_FACES: 8
  LV_FREETYPE_CACHE_FT_SIZES: 16
  LV_FREETYPE_CACHE_FT_GLYPH_CNT: 256
  LV_BIN_DECODER_RAM_LOAD: 1

32bit:
  LV_COLOR_DEPTH_32: 1
  LV_COLOR_DEPTH: 32

16bit:
  LV_COLOR_DEPTH_16: 1
  LV_COLOR_DEPTH: 16

perf:
  DEBUG_CUSTOMOPT: 1
  DEBUG_OPTLEVEL: "-O3"
  SCHED_INSTRUMENTATION: 0
  SCHED_IRQMONITOR: 0
  SCHED_CRITMONITOR: 0
  STACK_CANARIES: 0
  MM_KASAN: 0
  MM_BACKTRACE: -1
  LV_OBJ_STYLE_CACHE: 1
  LV_USE_ASSERT_NULL: 0
  LV_USE_ASSERT_MALLOC: 0
  LV_USE_ASSERT_STYLE: 0
  LV_USE_ASSERT_MEM_INTEGRITY: 0
  LV_USE_ASSERT_OBJ: 0

vg_lite:
  LV_USE_DRAW_VG_LITE: 1
  LV_VG_LITE_USE_GPU_INIT: 1
  LV_DRAW_BUF_ALIGN: 64
  LV_ATTRIBUTE_MEM_ALIGN_SIZE: 64
  LV_USE_VECTOR_GRAPHIC: 1
  LV_USE_FLOAT: 1
